heat_template_version: 2017-09-01

description: >
    Boot a VM, ease access to a remote host and return its IP address!

parameters:
    param_name:
        type: string
        description: Name of the server
    param_image:
        type: string
        description: Image to use for servers
        default: debian-9
    param_flavor:
        type: string
        description: Flavor to use for servers
        default: m1.small
    param_key:
        type: string
        description: Key name to use for servers
        default: admin
    param_remote_hostname:
        type: string
        description: Host name of the remote host
        default: provider
    param_remote_ip:
        type: string
        description: IP address of the remote host

resources:
    my_vm:
        type: "OS::Nova::Server"
        properties:
            name: { get_param: param_name }
            image: { get_param: param_image }
            flavor: { get_param: param_flavor } 
            key_name: { get_param: param_key }
            user_data:
                str_replace:
                    params:
                        ${HOSTNAME}: { get_param: param_remote_hostname }
                        ${IP_ADDRESS}: { get_param: param_remote_ip }
                    template: |
                        #!/bin/bash
                        # With the following line, the remote host is reachable from its hostname
                        echo "${IP_ADDRESS} ${HOSTNAME}" >> /etc/hosts

outputs:
    HOSTNAME:
        description: IP address of the created instance
        value: { get_attr: [my_vm, hostname] }
    HOSTIP:
        description: IP address of the created instance
        value: { get_attr: [my_vm, first_address] }

