heat_template_version: 2017-09-01

description: >
    Boot a VM and return its IP address!

resources:
    my_vm:
        type: "OS::Nova::Server"
        properties:
            name: hello_outputs
            image: debian-9
            flavor: m1.mini
            key_name: admin
            networks:
              - {network: private}

# We set here outputs (stack returned attributes).
# Outputs are defined by a name, and a set of properties:
outputs:
    HOSTIP:
        description: IP address of the created instance    # The name is optional
        value: { get_attr: [my_vm, first_address] }        # The value of this attribute
