heat_template_version: 2017-09-01

description: >
    Boot a VM with a post-installation script!

resources:
    my_vm:
        type: "OS::Nova::Server"
        properties:
            name: hello_cloud_init
            image: debian-9
            flavor: m1.mini
            key_name: admin
            networks:
              - {network: private}
            # We set here the user-data:
            user_data: |
                #!/usr/bin/env bash
                apt-get update
                apt-get install -y fortune fortunes cowsay lolcat
                echo -e "#!/bin/bash\n\nfortune | cowsay -n | lolcat\necho" \
                         > /etc/profile.d/cowsay.sh
