heat_template_version: 2017-09-01

description: >
  Deploy a WordPress application, composed of an SQL
  instance and an HTTP instance that serves WordPress.


parameters:
  ServerKeyName:
    label: Name of the SSH key to provide to cloud-init
    type: string
    default: admin

  # Parameters used in the cloud-init script to install & configure
  # MariaDB
  DBRootPassword:
    label: Value of the password to manage the database
    type: string
    default: 0p3nSt4cK
  DBName:
    label: Name of the database to create
    type: string
    default: wordpress
  DBUser:
    label: Name of the database user
    type: string
    default: donatello
  DBPassword:
    label: Password to access the database
    type: string
    default: leonardo

resources:
  database:
    type: ./db-vm.yaml
    properties:
      ServerKeyName: { get_param: ServerKeyName }
      DBRootPassword: { get_param: DBRootPassword }
      DBName: { get_param: DBName }
      DBUser: { get_param: DBUser }
      DBPassword: { get_param: DBPassword }
  wordpress:
    type: ./wp-vm.yaml
    properties:
      ServerKeyName: { get_param: ServerKeyName }
      DBName: { get_param: DBName }
      DBUser: { get_param: DBUser }
      DBPassword: { get_param: DBPassword }
      DBHost: { get_attr: [database, DBHost] }
