# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Ensure that the box is built with VirtIO Network Interface for
  # libvirt.  This is not the case of generic/ubuntu2004 which then
  # leads to issues with ovn geneve in OpenStack.
  config.vm.box = "peru/ubuntu-20.04-server-amd64"
  # config.vm.box = "peru/ubuntu-18.04-server-amd64"
  config.vm.box_version = "20201107.01"
  config.vm.box_check_update = false
  # Horizon dashboard
  config.vm.network :forwarded_port, guest: 80, host: 8080, host_ip: "*"
  # Horizon Spice Javascript console
  config.vm.network :forwarded_port, guest: 6082, host: 6082, host_ip: "*"
  # Optionally set the following private ip as a public ip of your
  # infrastructure
  config.vm.network :private_network, ip: "192.168.121.245"
  config.vm.synced_folder "./", "/vagrant", type: "rsync"

  config.vm.provider :virtualbox do |vb|
    # vb.memory = "8184"  # Minimum
    vb.memory = "16368"   # Much better
    vb.cpus = 4
    vb.gui = false
  end

  config.vm.provider :libvirt do |lv|
    # lv.memory = "8184"  # Minimum
    lv.memory = "16368"   # Much better
    lv.cpus = 4
    lv.nested = true
    lv.cpu_mode = "host-passthrough"
  end
end
