# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  # For horizon access
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # For WP access
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder './', '/vagrant', type: 'rsync'

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = "8092"
    libvirt.nested = true  # Enable nested virtualization
    libvirt.suspend_mode = "managedsave" # Free resources on suspend
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "8092"
  end
end
